# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=['MusicPlayer'],
    binaries=[],
    datas=[('resources', 'resources'), ('resources/icons', 'resources/icons'), ('resources/styles', 'resources/styles')],
    hiddenimports=[
        'MusicPlayer.player',
        'MusicPlayer.player.player',
        'MusicPlayer.ui.main_window',
        'MusicPlayer.ui.player_controller',
        'MusicPlayer.utils.metadata_manager',
        'MusicPlayer.utils.resource',
        'MusicPlayer.utils.style',
        'MusicPlayer.spotify',
        'MusicPlayer.cloud_service',
        'MusicPlayer.cloudmusic_service',
        'requests',
        'requests.packages.urllib3',
        'base64',
        'os',
        'vlc',
        'pygame._sdl2',
        'pygame.mixer',
        'pygame.font',
        'pygame.mixer_music',
        'pygame.time',
        'pygame.display',
        'pygame.event',
        'pygame.key',
        'pygame.mouse'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)